//! Load test utility for rak-basicstation.
//!
//! Simulates both sides simultaneously: a fake backend (Concentratord ZMQ or Semtech UDP)
//! injecting uplinks, and a fake LNS (WebSocket server) receiving them and optionally
//! sending downlinks back. Measures throughput, latency, and message loss.
//!
//! ```text
//! [Load Tester]                [rak-basicstation]              [Load Tester]
//!  Fake Backend  ──uplinks──►  Backend ──► LNS client  ──►   Fake LNS Server
//!  (ZMQ or UDP)  ◄──downlinks──         ◄── WebSocket ◄──   (WebSocket server)
//! ```
//!
//! Usage:
//!   cargo run --example load_test -- --rate 10 --duration 30
//!
//! Generate a matching rak-basicstation config:
//!   cargo run --example load_test -- --generate-config > /tmp/lt.toml
//!   cargo run -- -c /tmp/lt.toml

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use chirpstack_api::{gw, prost::Message};
use clap::Parser;
use futures_util::{SinkExt, StreamExt};
use tokio::net::{TcpListener, UdpSocket};

const DEV_ADDR: u32 = 0x2601_1234;
const EU868_FREQS: [u32; 8] = [
    868_100_000,
    868_300_000,
    868_500_000,
    867_100_000,
    867_300_000,
    867_500_000,
    867_700_000,
    867_900_000,
];

#[derive(Parser, Clone)]
#[command(name = "load_test", about = "Load test utility for rak-basicstation")]
struct Args {
    /// Uplinks per second
    #[arg(long, default_value = "10")]
    rate: u64,

    /// Test duration in seconds
    #[arg(long, default_value = "60")]
    duration: u64,

    /// Backend type: concentratord or semtech_udp
    #[arg(long, default_value = "concentratord")]
    backend: String,

    /// Fake LNS WebSocket listen address
    #[arg(long, default_value = "0.0.0.0:8887")]
    lns_bind: String,

    /// 16-char hex gateway EUI
    #[arg(long, default_value = "0016c001f156d7e5")]
    gateway_id: String,

    /// Fraction of uplinks triggering a downlink response
    #[arg(long, default_value = "0.1")]
    downlink_ratio: f64,

    /// ZMQ PUB socket bind address (concentratord backend)
    #[arg(long, default_value = "ipc:///tmp/lt_event")]
    zmq_event_bind: String,

    /// ZMQ REP socket bind address (concentratord backend)
    #[arg(long, default_value = "ipc:///tmp/lt_command")]
    zmq_command_bind: String,

    /// Semtech UDP target address
    #[arg(long, default_value = "127.0.0.1:1700")]
    udp_target: String,

    /// Print a matching rak-basicstation TOML config and exit
    #[arg(long)]
    generate_config: bool,
}

struct SharedState {
    metrics: Metrics,
    tracker: UplinkTracker,
    shutdown: AtomicBool,
    args: Args,
    ready: AtomicBool,
}

struct Metrics {
    uplinks_sent: AtomicU64,
    uplinks_received: AtomicU64,
    downlinks_sent: AtomicU64,
    downlinks_received: AtomicU64,
    latencies: Mutex<Vec<Duration>>,
    test_start: Mutex<Option<Instant>>,
}

struct UplinkTracker {
    timestamps: Mutex<HashMap<u32, Instant>>,
}

fn build_uplink_payload(seq: u32, dev_addr: u32) -> Vec<u8> {
    let mut payload = Vec::with_capacity(17);
    payload.push(0x40); // MHdr: unconfirmed data up
    payload.extend_from_slice(&dev_addr.to_le_bytes()); // DevAddr (4 bytes LE)
    payload.push(0x00); // FCtrl
    payload.extend_from_slice(&(seq as u16).to_le_bytes()); // FCnt (2 bytes LE)
    payload.push(0x01); // FPort = 1
    payload.extend_from_slice(&seq.to_be_bytes()); // FRMPayload = seq (4 bytes BE)
    payload.extend_from_slice(&[0x00; 4]); // MIC (dummy)
    payload
}

fn generate_config(args: &Args) {
    let backend = if args.backend == "semtech_udp" {
        "semtech_udp"
    } else {
        "concentratord"
    };

    let lns_host = if args.lns_bind.starts_with("0.0.0.0") {
        args.lns_bind.replacen("0.0.0.0", "127.0.0.1", 1)
    } else {
        args.lns_bind.clone()
    };

    println!(
        r#"# Auto-generated config for use with the load test utility.
# Generated by: cargo run --example load_test -- --generate-config

[logging]
  level = "warn"

[backend]
  enabled = "{backend}"
  gateway_id = "{gateway_id}"

  [backend.concentratord]
    event_url = "{event_url}"
    command_url = "{command_url}"

  [backend.semtech_udp]
    bind = "{udp_bind}"

[lns]
  server = "ws://{lns_host}"
  reconnect_interval = "1s"

[cups]
  enabled = false
"#,
        backend = backend,
        gateway_id = args.gateway_id,
        event_url = args.zmq_event_bind,
        command_url = args.zmq_command_bind,
        udp_bind = args.udp_target,
        lns_host = lns_host,
    );
}

/// EU868 router_config JSON sent to rak-basicstation on connection.
fn router_config_json() -> String {
    let mux_time = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs_f64();

    serde_json::json!({
        "msgtype": "router_config",
        "NetID": [0],
        "JoinEui": [[0, 0xFFFFFFFFFFFFFFFFu64]],
        "region": "EU868",
        "hwspec": "sx1301/1",
        "freq_range": [863000000, 870000000],
        "max_eirp": 16.0,
        "DRs": [
            [12, 125, 0],  // DR0: SF12/125
            [11, 125, 0],  // DR1: SF11/125
            [10, 125, 0],  // DR2: SF10/125
            [9, 125, 0],   // DR3: SF9/125
            [8, 125, 0],   // DR4: SF8/125
            [7, 125, 0],   // DR5: SF7/125
            [7, 250, 0],   // DR6: SF7/250
            [0, 0, 0],     // DR7: FSK
        ],
        "sx1301_conf": [{
            "radio_0": { "enable": true, "freq": 867500000 },
            "radio_1": { "enable": true, "freq": 868500000 },
            "chan_multiSF_0": { "enable": true, "radio": 1, "if": -400000 },
            "chan_multiSF_1": { "enable": true, "radio": 1, "if": -200000 },
            "chan_multiSF_2": { "enable": true, "radio": 1, "if": 0 },
            "chan_multiSF_3": { "enable": true, "radio": 0, "if": -400000 },
            "chan_multiSF_4": { "enable": true, "radio": 0, "if": -200000 },
            "chan_multiSF_5": { "enable": true, "radio": 0, "if": 0 },
            "chan_multiSF_6": { "enable": true, "radio": 0, "if": 200000 },
            "chan_multiSF_7": { "enable": true, "radio": 0, "if": 400000 },
            "chan_Lora_std": { "enable": true, "radio": 1, "if": -200000, "bandwidth": 250000, "spread_factor": 7 },
            "chan_FSK": { "enable": true, "radio": 1, "if": 300000, "bandwidth": 125000, "datarate": 50000 }
        }],
        "nocca": true,
        "nodc": true,
        "nodwell": true,
        "MuxTime": mux_time,
    })
    .to_string()
}

// ---------------------------------------------------------------------------
// Fake LNS server
// ---------------------------------------------------------------------------

async fn lns_server_task(state: Arc<SharedState>) {
    let listener = TcpListener::bind(&state.args.lns_bind)
        .await
        .unwrap_or_else(|e| panic!("Failed to bind LNS on {}: {}", state.args.lns_bind, e));
    println!("Fake LNS listening on {}", state.args.lns_bind);

    loop {
        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        let (stream, addr) = match listener.accept().await {
            Ok(v) => v,
            Err(e) => {
                eprintln!("LNS accept error: {}", e);
                continue;
            }
        };

        let state = state.clone();
        tokio::spawn(async move {
            if let Err(e) = lns_connection_handler(stream, addr, state).await {
                eprintln!("LNS connection error ({}): {}", addr, e);
            }
        });
    }
}

async fn lns_connection_handler(
    stream: tokio::net::TcpStream,
    addr: std::net::SocketAddr,
    state: Arc<SharedState>,
) -> anyhow::Result<()> {
    let ws_stream = tokio_tungstenite::accept_async(stream).await?;
    let (mut ws_write, mut ws_read) = ws_stream.split();

    // Read first message to detect connection type.
    let first_msg = ws_read
        .next()
        .await
        .ok_or_else(|| anyhow::anyhow!("No message received"))??;

    let text = match first_msg {
        tokio_tungstenite::tungstenite::Message::Text(t) => t.to_string(),
        _ => return Ok(()),
    };

    let parsed: serde_json::Value = serde_json::from_str(&text)?;

    // Discovery request: has "router" key, no "msgtype".
    if parsed.get("router").is_some() && parsed.get("msgtype").is_none() {
        let lns_host = if state.args.lns_bind.starts_with("0.0.0.0") {
            state.args.lns_bind.replacen("0.0.0.0", "127.0.0.1", 1)
        } else {
            state.args.lns_bind.clone()
        };

        let resp = serde_json::json!({
            "router": parsed["router"],
            "muxs": parsed["router"],
            "uri": format!("ws://{}", lns_host),
        });
        ws_write
            .send(tokio_tungstenite::tungstenite::Message::Text(
                resp.to_string().into(),
            ))
            .await?;
        println!("[LNS] Discovery from {} → {}", addr, lns_host);
        return Ok(());
    }

    // Main connection: first message should be "version".
    if let Some(msgtype) = parsed.get("msgtype").and_then(|v| v.as_str())
        && msgtype == "version"
    {
        let firmware = parsed
            .get("firmware")
            .and_then(|v| v.as_str())
            .unwrap_or("unknown");
        println!("[LNS] Main connection from {}, firmware: {}", addr, firmware);

        // Send router_config.
        let rc = router_config_json();
        ws_write
            .send(tokio_tungstenite::tungstenite::Message::Text(rc.into()))
            .await?;
        println!("[LNS] Sent router_config to {}", addr);

        // Signal readiness.
        state.ready.store(true, Ordering::Release);

        // Enter message loop.
        lns_message_loop(&mut ws_write, &mut ws_read, &state).await?;
    }

    Ok(())
}

async fn lns_message_loop(
    ws_write: &mut futures_util::stream::SplitSink<
        tokio_tungstenite::WebSocketStream<tokio::net::TcpStream>,
        tokio_tungstenite::tungstenite::Message,
    >,
    ws_read: &mut futures_util::stream::SplitStream<
        tokio_tungstenite::WebSocketStream<tokio::net::TcpStream>,
    >,
    state: &Arc<SharedState>,
) -> anyhow::Result<()> {
    let mut uplink_count: u64 = 0;
    let mut downlink_diid: i64 = 0;
    let downlink_interval = if state.args.downlink_ratio > 0.0 {
        (1.0 / state.args.downlink_ratio).round() as u64
    } else {
        0
    };

    while let Some(msg) = ws_read.next().await {
        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        let msg = msg?;
        let text = match msg {
            tokio_tungstenite::tungstenite::Message::Text(t) => t.to_string(),
            tokio_tungstenite::tungstenite::Message::Close(_) => break,
            _ => continue,
        };

        let parsed: serde_json::Value = match serde_json::from_str(&text) {
            Ok(v) => v,
            Err(_) => continue,
        };

        let msgtype = match parsed.get("msgtype").and_then(|v| v.as_str()) {
            Some(t) => t,
            None => continue,
        };

        match msgtype {
            "updf" => {
                uplink_count += 1;
                state
                    .metrics
                    .uplinks_received
                    .fetch_add(1, Ordering::Relaxed);

                // Extract seq from FRMPayload (4 bytes BE hex).
                if let Some(frm_hex) = parsed.get("FRMPayload").and_then(|v| v.as_str())
                    && let Ok(frm_bytes) = hex::decode(frm_hex)
                    && frm_bytes.len() == 4
                {
                    let seq = u32::from_be_bytes([
                        frm_bytes[0],
                        frm_bytes[1],
                        frm_bytes[2],
                        frm_bytes[3],
                    ]);
                    let mut tracker = state.tracker.timestamps.lock().unwrap();
                    if let Some(sent_at) = tracker.remove(&seq) {
                        let latency = sent_at.elapsed();
                        state.metrics.latencies.lock().unwrap().push(latency);
                    }
                }

                // Send downlink if configured.
                if downlink_interval > 0 && uplink_count % downlink_interval == 0 {
                    let xtime = parsed
                        .get("upinfo")
                        .and_then(|u| u.get("xtime"))
                        .and_then(|v| v.as_i64())
                        .unwrap_or(0);
                    let rctx = parsed
                        .get("upinfo")
                        .and_then(|u| u.get("rctx"))
                        .and_then(|v| v.as_i64())
                        .unwrap_or(0);
                    let freq = parsed.get("Freq").and_then(|v| v.as_u64()).unwrap_or(868_100_000);

                    downlink_diid += 1;
                    let dev_addr_le = DEV_ADDR.to_le_bytes();
                    let pdu = format!(
                        "60{}0000010001020304aabbccdd",
                        hex::encode(dev_addr_le)
                    );

                    let dnmsg = serde_json::json!({
                        "msgtype": "dnmsg",
                        "DevEui": "00-00-00-00-00-00-00-01",
                        "dC": 0,
                        "diid": downlink_diid,
                        "pdu": pdu,
                        "RxDelay": 1,
                        "RX1DR": 5,
                        "RX1Freq": freq,
                        "RX2DR": 0,
                        "RX2Freq": 869525000,
                        "xtime": xtime,
                        "rctx": rctx,
                        "priority": 0,
                    });

                    if ws_write
                        .send(tokio_tungstenite::tungstenite::Message::Text(
                            dnmsg.to_string().into(),
                        ))
                        .await
                        .is_ok()
                    {
                        state
                            .metrics
                            .downlinks_sent
                            .fetch_add(1, Ordering::Relaxed);
                    }
                }
            }
            "dntxed" => {
                // Downlink TX confirmation — just count it.
            }
            "timesync" => {
                // Respond with a timesync response.
                let txtime = parsed.get("txtime").and_then(|v| v.as_i64()).unwrap_or(0);
                let resp = serde_json::json!({
                    "msgtype": "timesync",
                    "txtime": txtime,
                });
                let _ = ws_write
                    .send(tokio_tungstenite::tungstenite::Message::Text(
                        resp.to_string().into(),
                    ))
                    .await;
            }
            _ => {}
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Fake Concentratord backend
// ---------------------------------------------------------------------------

fn zmq_rep_handler(state: Arc<SharedState>) {
    let ctx = zmq::Context::new();
    let cmd_sock = ctx.socket(zmq::REP).expect("REP socket");

    // Clean up stale IPC socket.
    if let Some(path) = state.args.zmq_command_bind.strip_prefix("ipc://") {
        let _ = std::fs::remove_file(path);
    }

    cmd_sock
        .bind(&state.args.zmq_command_bind)
        .unwrap_or_else(|e| panic!("ZMQ REP bind failed ({}): {}", state.args.zmq_command_bind, e));
    println!("ZMQ REP bound on {}", state.args.zmq_command_bind);

    loop {
        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        // Use a polling approach so we can check shutdown.
        if cmd_sock.poll(zmq::POLLIN, 500).unwrap_or(0) == 0 {
            continue;
        }

        let msg = match cmd_sock.recv_bytes(zmq::DONTWAIT) {
            Ok(m) => m,
            Err(_) => continue,
        };

        let cmd = match gw::Command::decode(msg.as_slice()) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("ZMQ cmd decode error: {}", e);
                let _ = cmd_sock.send(&b""[..], 0);
                continue;
            }
        };

        match cmd.command {
            Some(gw::command::Command::GetGatewayId(_)) => {
                let resp = gw::GetGatewayIdResponse {
                    gateway_id: state.args.gateway_id.clone(),
                };
                let _ = cmd_sock.send(resp.encode_to_vec(), 0);
            }
            Some(gw::command::Command::SetGatewayConfiguration(cfg)) => {
                println!(
                    "[ZMQ] SetGatewayConfiguration, channels: {}",
                    cfg.channels.len()
                );
                let _ = cmd_sock.send(&b""[..], 0);
            }
            Some(gw::command::Command::SendDownlinkFrame(dl)) => {
                state
                    .metrics
                    .downlinks_received
                    .fetch_add(1, Ordering::Relaxed);
                let ack = gw::DownlinkTxAck {
                    gateway_id: state.args.gateway_id.clone(),
                    downlink_id: dl.downlink_id,
                    items: vec![gw::DownlinkTxAckItem {
                        status: gw::TxAckStatus::Ok.into(),
                    }],
                    ..Default::default()
                };
                let _ = cmd_sock.send(ack.encode_to_vec(), 0);
            }
            _ => {
                let _ = cmd_sock.send(&b""[..], 0);
            }
        }
    }
}

fn zmq_pub_publisher(state: Arc<SharedState>) {
    let ctx = zmq::Context::new();
    let pub_sock = ctx.socket(zmq::PUB).expect("PUB socket");

    // Clean up stale IPC socket.
    if let Some(path) = state.args.zmq_event_bind.strip_prefix("ipc://") {
        let _ = std::fs::remove_file(path);
    }

    pub_sock
        .bind(&state.args.zmq_event_bind)
        .unwrap_or_else(|e| panic!("ZMQ PUB bind failed ({}): {}", state.args.zmq_event_bind, e));
    println!("ZMQ PUB bound on {}", state.args.zmq_event_bind);

    // Wait for readiness (rak-basicstation connected to LNS and received router_config).
    println!("Waiting for rak-basicstation to connect...");
    while !state.ready.load(Ordering::Acquire) {
        if state.shutdown.load(Ordering::Relaxed) {
            return;
        }
        std::thread::sleep(Duration::from_millis(100));
    }

    // Give concentratord subscriber time to connect.
    std::thread::sleep(Duration::from_secs(2));
    println!("Starting uplink generation (concentratord)...");

    // Record test start time.
    {
        let mut start = state.metrics.test_start.lock().unwrap();
        *start = Some(Instant::now());
    }

    let interval = if state.args.rate > 0 {
        Duration::from_secs_f64(1.0 / state.args.rate as f64)
    } else {
        Duration::from_secs(1)
    };

    let mut seq: u32 = 0;
    let test_end = Instant::now() + Duration::from_secs(state.args.duration);

    while Instant::now() < test_end {
        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        seq += 1;
        let freq = EU868_FREQS[(seq as usize) % EU868_FREQS.len()];
        let payload = build_uplink_payload(seq, DEV_ADDR);
        let context_val = (seq * 1000).to_be_bytes();

        let uplink = gw::UplinkFrame {
            phy_payload: payload,
            tx_info: Some(gw::UplinkTxInfo {
                frequency: freq,
                modulation: Some(gw::Modulation {
                    parameters: Some(gw::modulation::Parameters::Lora(
                        gw::LoraModulationInfo {
                            bandwidth: 125_000,
                            spreading_factor: 7,
                            code_rate: gw::CodeRate::Cr45.into(),
                            ..Default::default()
                        },
                    )),
                }),
            }),
            rx_info: Some(gw::UplinkRxInfo {
                uplink_id: seq,
                context: context_val.to_vec(),
                rssi: -60,
                snr: 10.0,
                crc_status: gw::CrcStatus::CrcOk.into(),
                ..Default::default()
            }),
            ..Default::default()
        };

        let event = gw::Event {
            event: Some(gw::event::Event::UplinkFrame(uplink)),
        };

        if pub_sock.send(event.encode_to_vec(), 0).is_ok() {
            state
                .metrics
                .uplinks_sent
                .fetch_add(1, Ordering::Relaxed);
            state
                .tracker
                .timestamps
                .lock()
                .unwrap()
                .insert(seq, Instant::now());
        }

        std::thread::sleep(interval);
    }
}

// ---------------------------------------------------------------------------
// Fake Semtech UDP backend
// ---------------------------------------------------------------------------

async fn udp_sender_task(state: Arc<SharedState>, socket: Arc<UdpSocket>) {
    // Wait for readiness.
    while !state.ready.load(Ordering::Acquire) {
        if state.shutdown.load(Ordering::Relaxed) {
            return;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }

    // Brief delay for the gateway to register via PULL_DATA.
    tokio::time::sleep(Duration::from_secs(2)).await;
    println!("Starting uplink generation (semtech_udp)...");

    // Record test start time.
    {
        let mut start = state.metrics.test_start.lock().unwrap();
        *start = Some(Instant::now());
    }

    let interval = if state.args.rate > 0 {
        Duration::from_secs_f64(1.0 / state.args.rate as f64)
    } else {
        Duration::from_secs(1)
    };

    let mut uplink_interval = tokio::time::interval(interval);
    let mut pull_interval = tokio::time::interval(Duration::from_secs(5));
    let gateway_id_bytes = hex::decode(&state.args.gateway_id).unwrap_or_else(|_| vec![0u8; 8]);
    let target: std::net::SocketAddr = state
        .args
        .udp_target
        .parse()
        .expect("Invalid UDP target address");

    let mut seq: u32 = 0;
    let mut token: u16 = 0;
    let test_end = Instant::now() + Duration::from_secs(state.args.duration);

    loop {
        if state.shutdown.load(Ordering::Relaxed) || Instant::now() >= test_end {
            break;
        }

        tokio::select! {
            _ = uplink_interval.tick() => {
                seq += 1;
                token = token.wrapping_add(1);
                let freq = EU868_FREQS[(seq as usize) % EU868_FREQS.len()];
                let payload = build_uplink_payload(seq, DEV_ADDR);

                let rxpk = serde_json::json!({
                    "rxpk": [{
                        "tmst": seq * 1000,
                        "freq": freq as f64 / 1_000_000.0,
                        "chan": (seq as usize % 8) as u32,
                        "rfch": 0,
                        "stat": 1,
                        "modu": "LORA",
                        "datr": "SF7BW125",
                        "codr": "4/5",
                        "rssi": -60,
                        "lsnr": 10.0,
                        "size": payload.len(),
                        "data": base64::Engine::encode(&base64::engine::general_purpose::STANDARD, &payload),
                    }]
                });

                let json_bytes = serde_json::to_vec(&rxpk).unwrap();
                let mut packet = Vec::with_capacity(12 + json_bytes.len());
                packet.push(0x02); // protocol version
                packet.extend_from_slice(&token.to_le_bytes());
                packet.push(0x00); // PUSH_DATA
                let gw_id: [u8; 8] = gateway_id_bytes[..8].try_into().unwrap_or([0u8; 8]);
                packet.extend_from_slice(&gw_id);
                packet.extend_from_slice(&json_bytes);

                if socket.send_to(&packet, target).await.is_ok() {
                    state.metrics.uplinks_sent.fetch_add(1, Ordering::Relaxed);
                    state.tracker.timestamps.lock().unwrap().insert(seq, Instant::now());
                }
            }
            _ = pull_interval.tick() => {
                // Send PULL_DATA to register the gateway.
                token = token.wrapping_add(1);
                let mut packet = Vec::with_capacity(12);
                packet.push(0x02); // protocol version
                packet.extend_from_slice(&token.to_le_bytes());
                packet.push(0x02); // PULL_DATA
                let gw_id: [u8; 8] = gateway_id_bytes[..8].try_into().unwrap_or([0u8; 8]);
                packet.extend_from_slice(&gw_id);
                let _ = socket.send_to(&packet, target).await;
            }
        }
    }
}

async fn udp_receiver_task(state: Arc<SharedState>, socket: Arc<UdpSocket>) {
    let mut buf = [0u8; 65535];

    loop {
        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        let result = tokio::time::timeout(Duration::from_secs(1), socket.recv_from(&mut buf)).await;

        let (size, remote) = match result {
            Ok(Ok(v)) => v,
            Ok(Err(_)) => continue,
            Err(_) => continue, // timeout
        };

        if size < 4 {
            continue;
        }

        match buf[3] {
            0x01 => {} // PUSH_ACK — ignore
            0x04 => {} // PULL_ACK — ignore
            0x03 => {
                // PULL_RESP — downlink received
                state
                    .metrics
                    .downlinks_received
                    .fetch_add(1, Ordering::Relaxed);

                // Send TX_ACK.
                let token = [buf[1], buf[2]];
                let gw_id = hex::decode(&state.args.gateway_id).unwrap_or_else(|_| vec![0u8; 8]);

                let ack_payload = serde_json::json!({"txpk_ack": {"error": "NONE"}});
                let ack_json = serde_json::to_vec(&ack_payload).unwrap();

                let mut ack = Vec::with_capacity(12 + ack_json.len());
                ack.push(0x02); // protocol version
                ack.extend_from_slice(&token);
                ack.push(0x05); // TX_ACK
                let gw_bytes: [u8; 8] = gw_id[..8].try_into().unwrap_or([0u8; 8]);
                ack.extend_from_slice(&gw_bytes);
                ack.extend_from_slice(&ack_json);
                let _ = socket.send_to(&ack, remote).await;
            }
            _ => {}
        }
    }
}

// ---------------------------------------------------------------------------
// Progress and reporting
// ---------------------------------------------------------------------------

async fn progress_reporter(state: Arc<SharedState>) {
    let mut interval = tokio::time::interval(Duration::from_secs(5));
    interval.tick().await; // skip first immediate tick

    loop {
        interval.tick().await;

        if state.shutdown.load(Ordering::Relaxed) {
            break;
        }

        let elapsed = {
            let start = state.metrics.test_start.lock().unwrap();
            match *start {
                Some(s) => s.elapsed().as_secs(),
                None => continue,
            }
        };

        let sent = state.metrics.uplinks_sent.load(Ordering::Relaxed);
        let received = state.metrics.uplinks_received.load(Ordering::Relaxed);
        let dl_sent = state.metrics.downlinks_sent.load(Ordering::Relaxed);
        let dl_recv = state.metrics.downlinks_received.load(Ordering::Relaxed);

        let pct = if sent > 0 {
            (received as f64 / sent as f64) * 100.0
        } else {
            0.0
        };
        let throughput = if elapsed > 0 {
            received as f64 / elapsed as f64
        } else {
            0.0
        };

        println!(
            "[{:>3}s] uplinks: {}/{} ({:.1}%) | downlinks: {}/{} | throughput: {:.1} msg/s",
            elapsed, received, sent, pct, dl_recv, dl_sent, throughput,
        );
    }
}

fn print_report(state: &SharedState) {
    let elapsed = {
        let start = state.metrics.test_start.lock().unwrap();
        match *start {
            Some(s) => s.elapsed().as_secs_f64(),
            None => state.args.duration as f64,
        }
    };

    let sent = state.metrics.uplinks_sent.load(Ordering::Relaxed);
    let received = state.metrics.uplinks_received.load(Ordering::Relaxed);
    let lost = sent.saturating_sub(received);
    let loss_pct = if sent > 0 {
        (lost as f64 / sent as f64) * 100.0
    } else {
        0.0
    };
    let throughput = if elapsed > 0.0 {
        received as f64 / elapsed
    } else {
        0.0
    };

    let dl_sent = state.metrics.downlinks_sent.load(Ordering::Relaxed);
    let dl_recv = state.metrics.downlinks_received.load(Ordering::Relaxed);

    let mut latencies = state.metrics.latencies.lock().unwrap();
    latencies.sort();
    let samples = latencies.len();

    let (p50, p95, p99, max) = if !latencies.is_empty() {
        let p = |pct: f64| {
            let idx = ((pct / 100.0) * (latencies.len() - 1) as f64).round() as usize;
            latencies[idx]
        };
        (p(50.0), p(95.0), p(99.0), *latencies.last().unwrap())
    } else {
        (Duration::ZERO, Duration::ZERO, Duration::ZERO, Duration::ZERO)
    };

    println!();
    println!("=== Load Test Report ===");
    println!("Duration:            {:.1}s", elapsed);
    println!("Backend:             {}", state.args.backend);
    println!("Rate (configured):   {} msg/s", state.args.rate);
    println!();
    println!("--- Uplinks ---");
    println!("  Sent:              {}", sent);
    println!("  Received:          {}", received);
    println!("  Lost:              {} ({:.2}%)", lost, loss_pct);
    println!("  Throughput:        {:.2} msg/s", throughput);
    println!();
    println!("--- Downlinks ---");
    println!("  Sent (by LNS):    {}", dl_sent);
    println!("  Received:          {}", dl_recv);
    println!();
    println!("--- Latency (end-to-end uplink) ---");
    println!("  Samples:           {}", samples);
    println!("  p50:               {:.2} ms", p50.as_secs_f64() * 1000.0);
    println!("  p95:               {:.2} ms", p95.as_secs_f64() * 1000.0);
    println!("  p99:               {:.2} ms", p99.as_secs_f64() * 1000.0);
    println!("  Max:               {:.2} ms", max.as_secs_f64() * 1000.0);
    println!("========================");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() {
    let args = Args::parse();

    if args.generate_config {
        generate_config(&args);
        return;
    }

    println!("=== rak-basicstation Load Test ===");
    println!("Backend:         {}", args.backend);
    println!("Rate:            {} msg/s", args.rate);
    println!("Duration:        {}s", args.duration);
    println!("LNS bind:        {}", args.lns_bind);
    println!("Gateway ID:      {}", args.gateway_id);
    println!("Downlink ratio:  {}", args.downlink_ratio);

    let state = Arc::new(SharedState {
        metrics: Metrics {
            uplinks_sent: AtomicU64::new(0),
            uplinks_received: AtomicU64::new(0),
            downlinks_sent: AtomicU64::new(0),
            downlinks_received: AtomicU64::new(0),
            latencies: Mutex::new(Vec::new()),
            test_start: Mutex::new(None),
        },
        tracker: UplinkTracker {
            timestamps: Mutex::new(HashMap::new()),
        },
        shutdown: AtomicBool::new(false),
        ready: AtomicBool::new(false),
        args: args.clone(),
    });

    // Start fake LNS server.
    let lns_state = state.clone();
    tokio::spawn(async move {
        lns_server_task(lns_state).await;
    });

    // Start progress reporter.
    let progress_state = state.clone();
    tokio::spawn(async move {
        progress_reporter(progress_state).await;
    });

    // Start backend.
    match args.backend.as_str() {
        "concentratord" => {
            println!("ZMQ event bind:  {}", args.zmq_event_bind);
            println!("ZMQ command bind: {}", args.zmq_command_bind);

            // REP handler (blocking, std thread).
            let rep_state = state.clone();
            std::thread::spawn(move || zmq_rep_handler(rep_state));

            // PUB publisher (blocking, std thread).
            let pub_state = state.clone();
            std::thread::spawn(move || zmq_pub_publisher(pub_state));
        }
        "semtech_udp" => {
            println!("UDP target:      {}", args.udp_target);

            // Bind on port 0 for sending; the receiver will get responses on the same socket.
            let socket = Arc::new(
                UdpSocket::bind("0.0.0.0:0")
                    .await
                    .expect("Failed to bind UDP socket"),
            );
            println!(
                "UDP local addr:  {}",
                socket.local_addr().unwrap()
            );

            let sender_state = state.clone();
            let sender_socket = socket.clone();
            tokio::spawn(async move {
                udp_sender_task(sender_state, sender_socket).await;
            });

            let receiver_state = state.clone();
            let receiver_socket = socket.clone();
            tokio::spawn(async move {
                udp_receiver_task(receiver_state, receiver_socket).await;
            });
        }
        other => {
            eprintln!("Unknown backend: {}. Use 'concentratord' or 'semtech_udp'.", other);
            std::process::exit(1);
        }
    }

    println!();
    println!("Waiting for rak-basicstation to connect...");
    println!("Start it with a matching config, e.g.:");
    println!("  cargo run --example load_test -- --generate-config > /tmp/lt.toml");
    println!("  cargo run -- -c /tmp/lt.toml");
    println!();

    // Wait for the test duration plus a grace period for readiness.
    // The actual timing is handled by the publisher threads.
    let total_wait = Duration::from_secs(args.duration + 300); // 5 min max wait for connection
    let start = Instant::now();

    loop {
        tokio::time::sleep(Duration::from_millis(500)).await;

        // If the test start has been recorded and duration has elapsed, stop.
        let test_started = state.metrics.test_start.lock().unwrap().is_some();
        if test_started {
            let test_start = state.metrics.test_start.lock().unwrap().unwrap();
            if test_start.elapsed() >= Duration::from_secs(args.duration) {
                // Give a short grace period for in-flight messages.
                tokio::time::sleep(Duration::from_secs(2)).await;
                break;
            }
        }

        if start.elapsed() >= total_wait {
            eprintln!("Timeout waiting for test to complete.");
            break;
        }
    }

    state.shutdown.store(true, Ordering::Release);

    // Brief pause for threads to clean up.
    tokio::time::sleep(Duration::from_millis(500)).await;

    print_report(&state);
}
